### ISSUE TITLE
update git tags to v1.6.1

### ISSUE THREAD

**Issue by maruilian11** [balupton/jquery-ajaxy#16]
hi, recently we are trying to add your lib to https://cdnjs.com, could you please update git tags to the latest version so that we can use **git auto-update** to add each released version to cdnjs.
thank you very much!

https://github.com/cdnjs/cdnjs/issues/7497

**Comment by balupton** [comment]
done thanks https://github.com/balupton/jquery-ajaxy/releases/tag/v1.6.1
